name: 'Deploy Defense Unicorns job scraper lambda'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
    run:
        shell: bash

jobs:

  deploy:
    name: Compile go binary
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 'stable'

    - name: build binary and zip
      run: make build
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - run: go mod download

    - uses: pulumi/actions@v6
      with:
        command: up
        stack-name: infrastructure
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
            
    

